### ISSUE TITLE
Dint work

### ISSUE THREAD

**Issue by amitguptagwl** [akimasa/kdbx-viewer#1]
I downloaded your application. Open HTML in browser. But nothing worked.

**Comment by akimasa** [comment]
Thank you for trying my app and let me know not working!
I made this app long time ago.
I don't have plan maintaining this app in future.

I confirmed that master branch doesn't work with today's Firefox browser.
There are another branch named "chrome".
This branch worked with today's Firefox.
Please try the "chrome" branch.

**Comment by amitguptagwl** [comment]
Thanks for your response. I found KeeWeb which has client for all the platforms + nice interface + web version as well. So I'll try that as well.
